version: "3.9"
services: 
  web: 
    build: web
    container_name: web
    # volumes: 
    #   - cdn-static-volume:/usr/share/nginx/html:ro
    ports: 
      - 5678:80
  backup: 
    build: backup
    container_name: backup
    # volumes: 
    #   - cdn-static-volume:/usr/share/nginx/html:ro
    ports: 
      - 5679:80
volumes: 
  cdn-static-volume:
