version: "3.9"
services:
  web:
    image: example-docker:latest
    container_name: web
    volumes:
      - example-docker-volume:/usr/share/nginx/html:ro
    ports:
      - 5679:80
volumes:
  example-docker-volume:
    external: true
    name: example-docker-volume
