# from the ./ directory, execute:
#   docker build -t dummy-web:latest .
#   docker stop dummy-instance
#   docker rm dummy-instance
#   docker run --name dummy-instance -p 5678:80 -d dummy-web
FROM nginx:stable
